version: '3.8'

services:
  mongo:
    image: mongo:latest  
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: supersecurepassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: